
package introsde.adapter.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdapterRunkeeper", targetNamespace = "http://ws.adapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdapterRunkeeper {


    /**
     * 
     * @param accessToken
     * @return
     *     returns introsde.adapter.ws.Activities
     */
    @WebMethod
    @WebResult(name = "fitnessActivities", targetNamespace = "")
    @RequestWrapper(localName = "getFitnessActivities", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetFitnessActivities")
    @ResponseWrapper(localName = "getFitnessActivitiesResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetFitnessActivitiesResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterRunkeeper/getFitnessActivitiesRequest", output = "http://ws.adapter.introsde/AdapterRunkeeper/getFitnessActivitiesResponse")
    public Activities getFitnessActivities(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns introsde.adapter.ws.Weights
     */
    @WebMethod
    @WebResult(name = "weight", targetNamespace = "")
    @RequestWrapper(localName = "getWeight", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetWeight")
    @ResponseWrapper(localName = "getWeightResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetWeightResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterRunkeeper/getWeightRequest", output = "http://ws.adapter.introsde/AdapterRunkeeper/getWeightResponse")
    public Weights getWeight(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "userId", targetNamespace = "")
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetUserIdResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterRunkeeper/getUserIdRequest", output = "http://ws.adapter.introsde/AdapterRunkeeper/getUserIdResponse")
    public Long getUserId(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns introsde.adapter.ws.Profile
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.adapter.ws.GetUserResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterRunkeeper/getUserRequest", output = "http://ws.adapter.introsde/AdapterRunkeeper/getUserResponse")
    public Profile getUser(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

}
